### ISSUE TITLE
Project create for Drupal 9 (BLT Version) fails to create database

### ISSUE THREAD

**Issue by mdyoung3** [acquia/drupal-recommended-project#25]
**Description**

Failure to install Drupal for `fin project create` and selecting number 2. Drupal 9 (BLT Version). 

**Steps to reproduce the issue:**

1. `fin project create`
2. Select `2.  Drupal 9 (BLT Version)`

**Describe the results you received:**

Fails to create database. It recommends creating it manually. Which I did, and I ran `fin init`  to only be met with the sam error.

![Screen Shot 2021-04-09 at 1 15 44 PM](https://user-images.githubusercontent.com/8387457/114229911-b42b8700-9935-11eb-9370-40449b725b94.png)

![Screen Shot 2021-04-09 at 1 29 19 PM](https://user-images.githubusercontent.com/8387457/114231441-b42c8680-9937-11eb-9641-5d11c071350c.png)

**Describe the results you expected:**

Database should be created on project create.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: bltd9
COMPOSE_FILE:
/Users/user/.docksal/stacks/volumes-nfs.yml
/Users/user/.docksal/stacks/stack-default.yml
/Users/user/Projects/bltd9/.docksal/docksal.yml
ENV_FILE:
/Users/user/Projects/bltd9/.docksal/docksal.env

PROJECT_ROOT: /Users/user/Projects/bltd9
DOCROOT: docroot
VIRTUAL_HOST: bltd9.docksal
VIRTUAL_HOST_ALIASES: *.bltd9.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DEFAULT_VERSION: null
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: bltd9.docksal
      GIT_USER_EMAIL: dude@organization.edu
      GIT_USER_NAME: John Doe
      HOST_GID: '20'
      HOST_UID: '502'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_ACQUIACLI_KEY: retracted
      SECRET_ACQUIACLI_SECRET: retracted
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: bltd9.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    healthcheck:
      interval: 10s
    hostname: cli
    image: docksal/cli:2.12-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - /tmp/.docksal/bltd9:/tmp/.docksal/bltd9:ro
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    healthcheck:
      interval: 10s
    hostname: db
    image: docksal/mysql:5.7
    logging:
      options:
        max-file: '10'
        max-size: 1m
    ports:
    - published: 0
      target: 3306
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    healthcheck:
      interval: 10s
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/user/Projects/bltd9
      io.docksal.virtual-host: bltd9.docksal,*.bltd9.docksal,bltd9.docksal.*
    logging:
      options:
        max-file: '10'
        max-size: 1m
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: :/Users/user/Projects/bltd9
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,actimeo=1
      type: nfs

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```

███  FIN
fin version: 1.103.0

███  OS
Darwin Mac OS X 10.15.7
Darwin UIT-C02D26LZMD6M 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : /Users

NFS EXPORTS:

# <ds-nfs docksal
/Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  DOCKER
EXPECTED CLIENT VERSION: 19.03.13
EXPECTED SERVER VERSION: 19.03.5

Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKER COMPOSE
EXPECTED VERSION: 1.27.4
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.2
docker-machine version 0.16.2, build bd45ab13

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v19.03.5

███  DOCKSAL: PROJECTS
project              STATUS                      virtual host                                                                           project root
bltd9                Up 18 minutes (healthy)     bltd9.docksal,*.bltd9.docksal,bltd9.docksal.*                                          /Users/User/Projects/bltd9
d7                   Exited (0) 19 hours ago     d7.docksal,*.d7.docksal,d7.docksal.*                                                   /Users/User/Projects/d7
noblestudy           Exited (0) 5 days ago       noblestudy.docksal,*.noblestudy.docksal,noblestudy.docksal.*                           /Users/User/Projects/noblestudy
ace-gryphon          Exited (0) 42 hours ago     ace-gryphon.docksal,*.ace-gryphon.docksal,ace-gryphon.docksal.*                        /Users/User/Projects/ace-gryphon
ace-orgpro      Exited (0) 2 days ago       ace-orgpro.docksal,*.ace-orgpro.docksal,ace-orgpro.docksal.*            /Users/User/Projects/ace-orgpro
acsf-cardinald7      Exited (0) 31 minutes ago   acsf-cardinald7.docksal,*.acsf-cardinald7.docksal,acsf-cardinald7.docksal.*            /Users/User/Projects/acsf-cardinald7
wp                   Exited (0) 2 weeks ago      wp.docksal,*.wp.docksal,wp.docksal.*                                                   /Users/User/Projects/wp
studylca             Exited (0) 5 days ago       studylca.docksal,*.studylca.docksal,studylca.docksal.*                                 /Users/User/Projects/studylca
d8                   Exited (0) 19 hours ago     d8.docksal,*.d8.docksal,d8.docksal.*                                                   /Users/User/Projects/d8
test-grunt           Exited (0) 2 weeks ago      test-grunt.docksal,*.test-grunt.docksal,test-grunt.docksal.*                           /Users/User/Projects/test-grunt
acsf-lelandd8        Exited (255) 3 days ago     acsf-lelandd8.docksal,*.acsf-lelandd8.docksal,acsf-lelandd8.docksal.*                  /Users/User/Projects/acsf-lelandd8
infounityhdfn        Exited (255) 3 weeks ago    infounityhdfn.docksal,*.infounityhdfn.docksal,infounityhdfn.docksal.*                  /Users/User/Projects/info.unityhdfn
acsf-cardinalsites   Exited (0) 19 hours ago     acsf-cardinalsites.docksal,*.acsf-cardinalsites.docksal,acsf-cardinalsites.docksal.*   /Users/User/Projects/acsf-cardinalsites
sws_soe_ace          Exited (255) 4 weeks ago    sws-soe-ace.docksal,*.sws-soe-ace.docksal,sws-soe-ace.docksal.*                        /Users/User/Dev/sws_soe_ace
cardinalatwork       Exited (0) 9 days ago       cardinalatwork.docksal,*.cardinalatwork.docksal,cardinalatwork.docksal.*               /Users/User/Projects/cardinalatwork
user                 Exited (255) 2 months ago   user.docksal,*.user.docksal,user.docksal.*                                             /Users/User/Projects/user
timer                Exited (0) 4 weeks ago      timer.docksal,*.timer.docksal,timer.docksal.*                                          /Users/User/Projects/timer
wordpress            Exited (0) 2 months ago     wordpress.docksal,*.wordpress.docksal,wordpress.docksal.*                              /Users/User/Projects/wordpress
journald             Exited (0) 2 months ago     journald.docksal,*.journald.docksal,journald.docksal.*                                 /Users/User/Dev/journald
swswpmigration       Exited (0) 2 months ago     swswpmigration.docksal,*.swswpmigration.docksal,swswpmigration.docksal.*               /Users/User/Projects/swswpmigration
blueprint            Exited (0) 3 months ago     blueprint.docksal,*.blueprint.docksal,blueprint.docksal.*                              /Users/User/Projects/blueprint
kidsmigrainestudy    Exited (0) 3 months ago     kidsmigrainestudy.docksal,*.kidsmigrainestudy.docksal,kidsmigrainestudy.docksal.*      /Users/User/Projects/kidsmigrainestudy
lumeostudy           Exited (0) 3 months ago     lumeostudy.docksal,*.lumeostudy.docksal,lumeostudy.docksal.*                           /Users/User/Projects/lumeostudy

███  DOCKSAL: VIRTUAL HOSTS
[0;32m*.bltd9.docksal[0m
[0;32mbltd9.docksal.*[0m
[0;32mbltd9.docksal[0m

███  DOCKSAL: NETWORKING

DOCKSAL_IP: 192.168.64.100
DOCKSAL_HOST_IP: 192.168.64.1
DOCKSAL_VHOST_PROXY_IP:
DOCKSAL_DNS_IP:
DOCKSAL_DNS_DISABLED: 0
DOCKSAL_NO_DNS_RESOLVER: 0
DOCKSAL_DNS_UPSTREAM:
DOCKSAL_DNS_DOMAIN: docksal

███  DOCKSAL: CONNECTIVITY

Host to 192.168.64.100: 	PASS
Container to 192.168.64.100: 	PASS
Container to 192.168.64.1: 	PASS

Checking connectivity to http://dns-test.docksal...
Host: PASS
Containers: PASS

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
285199b485d7        docksal/apache:2.4-2.3    "httpd-foreground"       18 minutes ago      Up 18 minutes (healthy)   80/tcp, 443/tcp                                          bltd9_web_1
31c2c05912de        docksal/cli:2.12-php7.3   "/opt/startup.sh sup…"   18 minutes ago      Up 18 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               bltd9_cli_1
794d73c53623        docksal/mysql:5.7         "docker-entrypoint.s…"   18 minutes ago      Up 18 minutes (healthy)   33060/tcp, 0.0.0.0:32768->3306/tcp                       bltd9_db_1
7a068599d856        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   24 minutes ago      Up 24 minutes (healthy)                                                            docksal-ssh-agent
402edafc609e        docksal/dns:1.1           "docker-entrypoint.s…"   24 minutes ago      Up 24 minutes (healthy)   192.168.64.100:53->53/udp                                docksal-dns
7140398aa41e        docksal/vhost-proxy:1.6   "docker-entrypoint.s…"   24 minutes ago      Up 24 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                    DRIVER              SCOPE
afec32020ca5        _default                bridge              local
0c0f0505087e        acsf-lelandd8_default   bridge              local
55b6bb34890f        bltd9_default           bridge              local
3341378fb385        bridge                  bridge              local
7755ca0dd4e3        host                    host                local
9b07aa9233d0        infounityhdfn_default   bridge              local
ea60c62827dd        none                    null                local
e0ce90a99799        sws_soe_ace_default     bridge              local
57921ca1ca2b        user_default            bridge              local

███  VIRTUALBOX
EXPECTED VERSION: 6.1.16
6.1.16r140961

███  DOCKSAL MOUNTS
192.168.64.1:/Users on /Users type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountport=987,mountproto=udp,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/User/Projects/bltd9 on /mnt/sda1/var/lib/docker/volumes/bltd9_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,noacl,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountport=987,mountproto=udp,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G     36.6G      7.1G  84% /mnt/sda1
  ```

</details>
